# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c1c4d45e44b798cd7b53809d41dff102fc21c43c54fa9e09279718bb10ff3cfcd6169a70f0ec21ba75d67ba315d87cc254009bd419a5f8ffc82658f61e77fad0

test:
  secret_key_base: db2b9b9afaf2ff71b9a6415968831365b67331fb6b7a47ca18a386ef21498bb71a84fb8087040a752c41fe5ed5e206d6a27208de23584932f0d67e0fc7a24524

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
